git:
  submodules: false
before_install:
 - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
 - git submodule update --init --recursive
language: java
jdk:
  - oraclejdk8
notifications:
  email: false
before_install:
 - chmod +x gradlew
after_success:
  - bash <(curl -s https://codecov.io/bash)
