version: "3"
services:
#  jungletree:
#    image: 'jungletree/jungletree'
#    depends_on:
#     - jms
#     - storage
#    links:
#     - jms
#    environment:
#      MESSAGE_BROKER_URL: 'nio://localhost:61616'
#      MESSAGE_TIMEOUT: '1000'

#  storage:
#    image: 'jungletree/jungletree'
#    depends_on:
#     - jms
#     - db
#    links:
#     - jms
#     - db

  db:
    restart: always
    image: 'library/postgres'
    environment:
      POSTGRES_PASSWORD: 'changeme'
    volumes:
      - 'db:/var/lib/postgresql'

  jms:
    image: 'webcenter/activemq'
    ports:
     - '8161:8161'
     - '61613:61613'
     - '61616:61616'
    volumes:
     - 'jms:/data/activemq'
     - 'jms:/var/log/activemq'
    environment:
      ACTIVEMQ_NAME: 'jungletree_mq'
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'true'
      ACTIVEMQ_ADMIN_LOGIN: 'admin'
      ACTIVEMQ_ADMIN_PASSWORD: 'admin'
      ACTIVEMQ_WRITE_LOGIN: 'jungletree'
      ACTIVEMQ_WRITE_PASSWORD: 'changeme'
      ACTIVEMQ_READ_LOGIN: 'jungletree'
      ACTIVEMQ_READ_PASSWORD: 'changeme'
      ACTIVEMQ_JMX_LOGIN: 'jungletree'
      ACTIVEMQ_JMX_PASSWORD: 'changeme'
      ACTIVEMQ_MIN_MEMORY: 16
      ACTIVEMQ_MAX_MEMORY: 2048
      ACTIVEMQ_ENABLED_SCHEDULER: 'true'
      ACTIVEMQ_STATIC_TOPICS: ''
      ACTIVEMQ_STATIC_QUEUES: ''
volumes:
  db:
  jms:
