version: '2'
services:
  activemq:
    image: 'webcenter/activemq'
    ports:
     - '8161:8161'
     - '61613:61613'
     - '61616:61616'
    volumes:
     - '/data/activemq:/data/activemq'
     - '/var/log/activemq:/var/log/activemq'
    environment:
      ACTIVEMQ_NAME: 'jungletree_mq'
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'true'
      ACTIVEMQ_ADMIN_LOGIN: 'admin'
      ACTIVEMQ_ADMIN_PASSWORD: 'changeme'
      ACTIVEMQ_WRITE_LOGIN: 'producer'
      ACTIVEMQ_WRITE_PASSWORD: 'changeme'
      ACTIVEMQ_READ_LOGIN: 'consumer'
      ACTIVEMQ_READ_PASSWORD: 'changeme'
      ACTIVEMQ_JMX_LOGIN: 'jmx'
      ACTIVEMQ_JMX_PASSWORD: 'changeme'
      ACTIVEMQ_MIN_MEMORY: 16
      ACTIVEMQ_MAX_MEMORY: 2048
      ACTIVEMQ_ENABLED_SCHEDULER: 'true'
      ACTIVEMQ_STATIC_TOPICS: 'topic1;topic2;topic3'
      ACTIVEMQ_STATIC_QUEUES: 'queue1;queue2;queue3'
