version: "3"
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    ports:
    - '5672:5672'
    - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: jungletree
      RABBITMQ_DEFAULT_PASS: changeme
volumes:
  rabbitmq:
